### ISSUE TITLE
A real cable for the MIDI …

### ISSUE THREAD

**Issue by mithrendal** [PTz0uAH/AmiGoDOS#1]
Did you know 🙃? There is also a serial web API …

I have tried the following app and could communicate with that with my old rusty Amiga 1000 via a physical serial cable

https://googlechromelabs.github.io/serial-terminal/

You might also would like to have a look on this
https://caniuse.com/web-serial

**Comment by PTz0uAH** [comment]
@mithrendal welcome and yes I know of those API's but I work with Firefox as reference and that serial web API is not supported.. so I use the WebMIDI API and now it plays directly from Music-X.. via maudio midisport2x2 and can also redirect via rtpMIDI.. if needed.. for now only output is working.. but midi input is WIP..

btw you can visit the beta running at https://amigoxpe.net/TS0CA/AmiGoDOS.php
+ today I made the TS0CA repository available.. (codename vBerlin) you might want to take a look at it..

I put a lot of effort in IT to get it done before that memorable date of April the 30th..

Thanks for the links.. I only used Chromium for its easy sandboxless NPAPI capability because there was a Delphi API available but the one I used does not work anymore so if I can find an updated Chromium API I might be able to test and/or include the above recommendations when I find the time.. first things first.. getting those MIDI-inputs working..

p.s. I found a possible workaround for the lacking serial API in Firefox.. using the mechanism the Arduino IDE Web Edition uses to communicate to physical MCU devices and using its serial monitor capabilities.. I created some midi capable hardware based on Mega2650 which also relays AUX: at 31250 BAUD.. connected to the A1200..

**Comment by PTz0uAH** [comment]
@mithrendal just for your information.. I have started exploring the Chromium/Chrome infrastructure to test the case you have sketched.. it seems the serialport latency (for midi) is the lowest at Chrome so lets see if I can get it to work..

**Comment by PTz0uAH** [comment]
hoi @mithrendal I have updated AmiGoDOS with 2 major functions..

1) activating the WebSerialAPI works for chromium..

2) the pseudo-nullmodem also works using 2 instances of vAmigaWeb although there is some latency..

There is a demopage at TS0CA_ROOT/AmiGoSER.htm you may test if you like..

as the nullmodem worked fine with Blitz2 example TERMINAL.BB.. I needed also a game to test..

so here a little demo of my first BattleChess play showcasing the NULLMODEM mode of AmiGoDOS..

![BattleChess_works](https://github.com/PTz0uAH/AmiGoDOS/assets/87427309/48fcb770-1323-47bc-a1c3-b88c1c0c588d)

https://github.com/PTz0uAH/AmiGoDOS/assets/87427309/24cc000b-ed08-41ba-a676-b7e85c106432

hope you like it so far..

**Comment by mithrendal** [comment]
I tried it in Safari. it works nicely although I did not know what the `engage` command is for and it throwed an error (maybe because of safari browser?)... nevertheless the `nullmodem init` command established the connection and I could play against the other Amiga instance... 

<img width="967" alt="image" src="https://github.com/PTz0uAH/AmiGoDOS/assets/17108995/8605fbaf-c988-4b7d-b8da-1f88754a355f">

very cool stuff! this works with the virtual null modem cable and not with the WebSerialAPI right ?

when using the WebSerialAPI, one could dream further of playing over the LAN or internet with some software that bridges serial to ethernet maybe something like this https://www.serial-over-ethernet.com (I just searched google for connecting the serial port to the internet don't know whether that brigdeing software works, just pasted the first result here, their video looks like this is the right thing for it ) 


EDIT:
oh wow that mentioned software is not free and very expensive

I found a free tool which should do, the following article explains it (it is in german maybe you have to translate it)

https://crycode.de/serielle-schnittstelle-ueber-ethernet

another windows free tool for bringing ser: to lan: mentioned by that article is https://www.serialporttool.com/GK/comm-tunnel/

**Comment by PTz0uAH** [comment]
Hoi @mithrendal..

to prevent errors in the "engage" startup please configure a vAmigaWeb machine first run amy or buffy (lowercase) and save the snapshot as the Name of the particular "lady"..  i.e. save snapshot as Amy , Buffy, Claire.. etc. (see code) and case-sensitive.. then the "engage command" will boot the snapshot.. after reloading the initial page..

> works with the virtual null modem cable and not with the WebSerialAPI right ?

indeed the "virtual cable" also works for browsers which have no WebSerial API access.. via modes NULLMODEM1 & NULLMODEM2..

But lets first share some wonderfull progress.. I dived into the WebSerial stuff and introduced NULLMODEM0 mode which works via the WebSerial API and tested BattleChess with my A500 rev.5 unexpanded connected via 3wire nullmodemcable.. demopage at [TS0CA_ROOT/AmiGoNET.htm].. which expects a "BattleChess" snapshot "Claire" on the left and also "Buffy" on the right.. which could have any function except nullmodem.. for this beta.. IYKWIM..

![AmiGoDOS_Demo_HWSerial_NullModem](https://github.com/PTz0uAH/AmiGoDOS/assets/87427309/af3af687-b7ef-4820-bd9c-7dff75c8fb74)

![PB280397](https://github.com/PTz0uAH/AmiGoDOS/assets/87427309/47440b49-40f9-46a7-9d75-2bc6ca63721e)

And yes lan/netplay would be an excellent addition but I've noticed a lot of overhead using the PostMessage constructions (WebSerial API/WebMIDI API).. firing at every byte.. creating latency.. especially if using "highspeed" baudrates like MIDI.. at 31250 baud.. it would be nice to reduce overhead and maybe additional even connect via some kind of TCP port on the vAmiga-core.. (so I can connect directly to my native AmiGoDOS application called "NewShell").. hmm just thinking ahead..

"Now we're getting somewhere" :-)

**Comment by PTz0uAH** [comment]
Hoi @mithrendal..

Here the latest progress concerning the initial question about the physical "MIDI cable"..

I guess we are almost there.. so AmiGoDOS can use WebSerial API via NULLMODEM0 mode and also via the WebMIDI API via the MIDI modes.. which is versatile..

With the AmiGoDOS NULLMODEM0 at PC side configured at 28K8 baud (31250 gave an error.. being a limitation of the PC build-in chipset) I could to my surprise test the duplex MIDI connectivity with success..

Some observations:
1) MIDI works rather well even with midiclocks enabled.. yet there is some lag
![20231201_141242](https://github.com/PTz0uAH/AmiGoDOS/assets/87427309/3c1fbbeb-334a-4237-a0a2-d398453ff885)

![webserial_latency_20231201_141347](https://github.com/PTz0uAH/AmiGoDOS/assets/87427309/edf0a622-c294-4789-a87d-074fd6686a7c)

2) The most annoying lag is audible when a sample metronome is used.. I can't pinpoint exactly what the problem is.. have to investigate more..

https://github.com/PTz0uAH/AmiGoDOS/assets/87427309/3846eaf3-9e99-4953-b29f-3bf75a19acb7

I hope we can tackle the latency thing somehow.. but for now I am glad basic functionality works..

**Comment by mithrendal** [comment]
what you have achieved is really incredible ... you connected above `vAmigaWeb` which lives in a web browser to a real `A500 rev.5 unexpanded` connected via 3wire nullmodemcable .. what a cool thing  😎! 

>I hope we can tackle the latency thing somehow.. but for now I am glad basic functionality works..

two things come to my mind.

1. vAmigaWeb still uses the 2.3 core from @dirkwhoffmann. In version 2.4 he refactored the serial port. He upgraded the MSG_SER_OUT event in order that it can give vAmigaWeb more than one byte at a time. We can adapt the post method to `AmiGoDOS` which currently transports only 1 byte to one that can transport all remaining bytes at once. That way we would reduce messaging overhead

```javascript
window.parent.postMessage({ msg: 'serial_port_out', value: data},"*");

```

2. vAmigaWeb is driven by the frame rate of your screen. I.e. when your host screen is 60hz and vAmigaWeb tries to emulate the Amiga at 50Hz then it has to sync each 1/50 = 20ns amiga frame into an 1/60 = 16.6ns host frame. You see the n+1 frame is either to late or too early

```
host 0 ms-> render Amiga 20 ms
host 16.6 ms-> host is too early for next frame do nothing
host 33.2 ms-> host is a bit late for Amiga 20ms, render Amiga 40 ms
host 49.8 ms-> to early do nothing
host 66.4 ms-> render Amiga 60 ms
host 83   ms-> render  Amiga 80 ms
...

```

So on a 60hz screen you would typically see a deviation which is between 0 - 16.6 ms.
When you connect it to a monitor with 50Hz frame rate then this time deviation would be removed.

```
host 20ms -> Amiga  20ms
host 40ms -> Amiga 40ms
host 60 ms -> Amiga 60ms
...
```

When you cannot change the host display rate of 60 hz then you could try to set vAmiga to emulate an NTSC Amiga which also runs at 60 Hz which would also result in exact timing and very low deviation.

maybe you have to configure something in music x for this ? 

see the following statement from https://www.muzines.co.uk/articles/music-x/5672

_- music x has frame rates for NTSC (29.97 frames per second) and PAL (25 frames per second) built in, so you can sync to these TV standards. Good for pond-hopping TV musicians._


@PTz0uAH does that makes sense ? @dirkwhoffmann are my observations / assumptions / thoughts correct ?

**Comment by mithrendal** [comment]
@PTz0uAH I have build vAmigaWeb with the latest core written by @dirkwhoffmann . It should already out of the box reduce the serial overhead a bit ... more performance improvement would be possible when we reduce the postMessage calls in case there are more bytes pending to be sent into AmiGoDOS by sending the whole bulk of pending bytes at once.  I would suggest we first test the serial support in vAmigaCore 2.4 since it has been reworked ... hoping it still works well

build folder where you can download
https://github.com/vAmigaWeb/uat

run 
https://vamigaweb.github.io/uat

**Comment by PTz0uAH** [comment]
@mithrendal that is great news..

I will test the new vAmigaWeb build asap.. and report back the results overhere..

Though I am still struggling to get 50hz displayed in a proper way.. it's a bit ironic the latest version of Music-X was adapted for the PAL market segment while 60hz was already default in the internal math.. being NTSC optimised initially.. maybe it's indeed wise/easier to try the NTSC mode of vAmigaWeb and find out if that has a positive impact on the latency..

Furthermore I am also testing an experimental pc-Arduino serial connection to adapt to the baudrate from/to Amiga side conform MIDI standard 31250 baud..

Now lets see what it brings..

**Comment by PTz0uAH** [comment]
@mithrendal

preliminary test of the 2.4 core gives a strong regression.. Music-X Amiga to vAmigaWeb runs stuttering in sync and the other way around vAmigaWeb to Amiga does not work at all overhere.. need to test more.. maybe I missed something.. but 2.3 runs way smoother so it seems..

**Comment by mithrendal** [comment]
@PTz0uAH  ok I will do some tests on my side too. Also I will check the relevant code paths …

**Comment by mithrendal** [comment]
confirmed something seems wrong with vAmigaWeb and the new core 2.4 ... It runs much much slower

<img width="1171" alt="image" src="https://github.com/PTz0uAH/AmiGoDOS/assets/17108995/dff14282-fb6f-462f-9648-62b056b70db8">

vAmigaWeb 2.3 consumes 20% CPU
vAmigaWeb 2.4 consumes 35% CPU 

needs more investigation in the coming days... I bet I did something wrong when merging the new core into vAmigaWeb

**Comment by PTz0uAH** [comment]
@mithrendal  well good luck with that!

FYI.. the AmiGoDOS path for vAmigaWeb v2.4-core experiments can be found at [AMIGOXPE_ROOT]/TS0CA_UAT/AmiGoDOS.php

I introduced NULLMODEM0_BETA mode for the Music-X defacto.std. 2.4-core test..

Parameters: AmiGoDOS.php?amiga=Gwen&mode=11&baudrate=28800&autoboot

A saved Music-X snapshot to "Gwen" needs to be available though.. ( I use kick3.1 rom but lowering the specs may also have a positive impact on latency so I have to experiment some more.. )

It's approximately the same setup as with the previous successfully conducted 2.3 tests..

Anyways.. I hope you can track down what caused the 2.4 anomalies..

**Comment by mithrendal** [comment]
>Anyways.. I hope you can track down what caused the 2.4 anomalies..

the anomalies have been tracked down see here

https://github.com/dirkwhoffmann/vAmiga/issues/801

a fix is underway 😎
